[OPS-2326] versioning du code des lambdas et du template cloudformation
Next-Interactive/video-on-demand-on-aws-foundation pull request #1
Opened 2023-03-14 09:49 UTC by eboulfakhr

PR pour valider la procédure de build décrite dans le readme.  
Le dépôt a été forké pour permettre de rajouter ensuite des petites customisations dans un second temps.
- suivi de la procédure décrite dans le readme pour builder les lambdas et générer un template cloudformation.
  - Le bucket utilisé pour ce test est `s3://test-vod-deployments-sandbox-next-eu-west-1`.  
  - La stack cloudformation a été déployée OK

2023-03-15 13:17 UTC, nass-altice requested changes
J'ai du mal à comprendre pourquoi tu commites des zip ?

2023-03-15 13:17 UTC, na-rmcbfm commented on deployment/global-s3-assets/video-on-demand-on-aws-foundation.template
> +        "Data": "Yes"
```suggestion
        "Data": "No"
```

2023-03-27 09:56 UTC, eboulfakhr commented on deployment/global-s3-assets/video-on-demand-on-aws-foundation.template
> +        "Data": "Yes"
c'est fix. fait à la source CDK

2023-03-28 15:07 UTC, eboulfakhr commented on deployment/global-s3-assets/video-on-demand-on-aws-foundation.template
> +        "Data": "Yes"
pour le rajout des zips, c'est pour illustrer ce qui est produit par le build (template cloudformation en `global-s3-assets` et zip des lambdas en `regional-s3-assets`).
à voir ce qu'on définit dans notre procédure de build.

2023-03-30 11:42 UTC, nass-altice approved these changes

2023-03-30 11:43 UTC, nass-altice commented
@eboulfakhr le "reste à faire" est consigné quelque part sur Jira ?

2023-03-30 13:19 UTC, merged